# Generated by Django 4.2 on 2025-12-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('xhs', '小红书'), ('douyin', '抖音'), ('api', '外部 API')], default='telegram', help_text='数据来源平台', max_length=50)),
                ('source_type', models.CharField(choices=[('telegram_channel', 'Telegram 频道'), ('telegram_group', 'Telegram 群组'), ('telegram_user', 'Telegram 用户'), ('external_api', '外部 API')], max_length=50)),
                ('channel_id', models.BigIntegerField(blank=True, help_text='频道/群组 ID', null=True)),
                ('channel_username', models.CharField(blank=True, help_text='@username', max_length=255, null=True)),
                ('channel_name', models.CharField(blank=True, help_text='频道名称', max_length=255, null=True)),
                ('data_type', models.CharField(choices=[('media', '媒体文件'), ('comment', '评论'), ('post', '帖子'), ('tguser', '用户数据'), ('post_tguser', '帖子 + 用户')], default='post', max_length=20)),
                ('fetch_mode', models.CharField(choices=[('forward', '从最新往前抓'), ('backward', '从最旧往后抓')], default='forward', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='是否启用抓取')),
                ('last_message_id', models.BigIntegerField(blank=True, help_text='上次抓取的 message_id', null=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, help_text='上次抓取时间', null=True)),
                ('extra_config', models.JSONField(blank=True, help_text='额外配置，如过滤规则、解析规则等', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
