# Generated by Django 4.2 on 2026-01-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionsource',
            name='fetch_mode',
            field=models.CharField(choices=[('forward', '从最新往前抓（增量抓取）'), ('backward', '从最旧往后抓（补档）')], default='forward', max_length=20),
        ),
    ]
