# Generated by Django 4.2 on 2025-12-25 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='场所名')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='场所简称')),
                ('city', models.CharField(max_length=100, verbose_name='城市')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='区域')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='地址')),
                ('exchange_points', models.PositiveIntegerField(default=0, help_text='0 表示不可兑换', verbose_name='兑换所需积分')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '场所',
                'verbose_name_plural': '场所',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='编号')),
                ('nickname', models.CharField(blank=True, max_length=120, verbose_name='昵称')),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='出生年份')),
                ('bust_info', models.CharField(blank=True, max_length=50, verbose_name='胸围信息')),
                ('attractiveness', models.PositiveSmallIntegerField(blank=True, help_text='0-100 分制', null=True, verbose_name='颜值评价')),
                ('extra_info', models.TextField(blank=True, verbose_name='其他信息')),
                ('is_active', models.BooleanField(default=True, verbose_name='在职/可用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='places.place')),
            ],
            options={
                'verbose_name': '服务人员',
                'verbose_name_plural': '服务人员',
            },
        ),
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='营销名')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='电话')),
                ('wechat', models.CharField(blank=True, max_length=100, verbose_name='微信')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketings', to='places.place')),
            ],
            options={
                'verbose_name': '场所营销',
                'verbose_name_plural': '场所营销',
            },
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['place', 'code'], name='places_staf_place_i_072d23_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['place', 'nickname'], name='places_staf_place_i_59cc72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marketing',
            unique_together={('place', 'name')},
        ),
    ]
