# Generated by Django 4.2 on 2025-12-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='staff',
            name='places_staf_place_i_072d23_idx',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='code',
        ),
        migrations.AddField(
            model_name='staff',
            name='bust_size',
            field=models.CharField(blank=True, max_length=50, verbose_name='胸围大小'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='attractiveness',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='颜值评价'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='bust_info',
            field=models.CharField(blank=True, max_length=240, verbose_name='胸围信息'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='nickname',
            field=models.CharField(blank=True, max_length=120, verbose_name='号码/昵称'),
        ),
    ]
