# Generated by Django 4.2 on 2025-12-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_staff_places_staf_place_i_072d23_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='birth_year',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='出生年份'),
        ),
    ]
