# Generated by Django 4.2 on 2025-12-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_staff_birth_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='attractiveness',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='bust_info',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='bust_size',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='extra_info',
        ),
        migrations.AlterField(
            model_name='staff',
            name='nickname',
            field=models.CharField(max_length=120, verbose_name='号码/昵称'),
        ),
    ]
