# Generated by Django 4.2 on 2025-12-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_staff_attractiveness_remove_staff_birth_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketing',
            name='qr_or_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='marketing/qrcodes/', verbose_name='二维码/微信截图'),
        ),
    ]
