# Generated by Django 4.2 on 2026-01-06 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_marketing_qr_or_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='first_letter',
            field=models.CharField(blank=True, max_length=12, verbose_name='场所首字母'),
        ),
        migrations.CreateModel(
            name='PlaceFormerName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='简称')),
                ('first_letter', models.CharField(blank=True, max_length=12, verbose_name='首字母')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='former_names', to='places.place')),
            ],
            options={
                'verbose_name': '场所曾用名',
                'verbose_name_plural': '场所曾用名',
            },
        ),
    ]
