# Generated by Django 4.2 on 2025-12-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_in_keywords', models.TextField(default='签到')),
                ('sign_in_points', models.IntegerField(default=10)),
                ('message_min_length', models.IntegerField(default=10)),
                ('message_base_points', models.IntegerField(default=2)),
                ('message_daily_limit', models.IntegerField(default=50)),
                ('crit_rate', models.FloatField(default=0.1)),
                ('crit_multiplier', models.IntegerField(default=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
