# Generated by Django 4.2 on 2025-12-25 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('points', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=0)),
                ('is_bot', models.BooleanField(default=False)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否为管理员')),
                ('is_merchant', models.BooleanField(default=False, verbose_name='是否为商家')),
                ('is_super_admin', models.BooleanField(default=False, verbose_name='是否为超级管理员')),
                ('has_interacted', models.BooleanField(default=False, verbose_name='是否有过交互')),
                ('last_sign_in_date', models.DateField(blank=True, null=True, verbose_name='最后签到日期')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroupStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('daily_message_count', models.IntegerField(default=0)),
                ('daily_points_earned', models.IntegerField(default=0)),
                ('last_message_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_stats', to='tgusers.telegramuser')),
            ],
            options={
                'unique_together': {('user', 'chat_id')},
            },
        ),
    ]
