# Generated by Django 4.2 on 2025-12-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='experiences',
            field=models.IntegerField(default=0, verbose_name='经验值'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='inheritance_code',
            field=models.UUIDField(blank=True, default=None, editable=False, null=True, unique=True, verbose_name='继承码'),
        ),
    ]
