# Generated by Django 4.2 on 2025-12-26 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collect', '0003_alter_submission_options_and_more'),
        ('places', '0004_remove_staff_attractiveness_remove_staff_birth_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('vote', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.submission')),
            ],
            options={
                'unique_together': {('submission', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='StaffInactiveReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.staff')),
            ],
            options={
                'unique_together': {('staff', 'user_id')},
            },
        ),
    ]
