# Generated by Django 4.2 on 2025-12-28 13:25

from django.db import migrations, models
import django.db.models.deletion
import mall.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tgusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MallProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('description', models.TextField(verbose_name='商品描述')),
                ('points_needed', models.IntegerField(default=0, verbose_name='所需积分')),
                ('coins_needed', models.IntegerField(default=0, verbose_name='所需金币')),
                ('stock', models.IntegerField(default=0, verbose_name='库存数量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '商城商品',
                'verbose_name_plural': '商城商品',
            },
        ),
        migrations.CreateModel(
            name='RedemptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(default=mall.models.generate_verification_code, max_length=32, unique=True, verbose_name='核销码')),
                ('status', models.CharField(choices=[('pending', '待核销'), ('used', '已核销'), ('expired', '已过期')], default='pending', max_length=20, verbose_name='状态')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, verbose_name='兑换时间')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='核销时间')),
                ('verified_by', models.BigIntegerField(blank=True, null=True, verbose_name='核销管理员ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='mall.mallproduct', verbose_name='兑换商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='tgusers.telegramuser', verbose_name='兑换用户')),
            ],
            options={
                'verbose_name': '兑换记录',
                'verbose_name_plural': '兑换记录',
            },
        ),
    ]
