"""
Django settings for huisuobot project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@5&xl9t21j&il72ag0un^*$cj#bha0=6+x=4-0kh&fr(klvhc)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# Application definition

INSTALLED_APPS = [
    'tgusers',
    'mygroups',
    'collect',
    'botconfig',
    'bot_core',
    'reports',
    'places',
    'common',
    'interactions',
    'telethon_account',
    'ingestion',
    'mall',
    'lottery',
    'django_q',
    'storages',
    'tgfunc_carousel',
    'django_apscheduler',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'huisuobot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'huisuobot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Q_CLUSTER 配置
Q_CLUSTER = {
    'name': 'shuilaoban', #项目名
    'workers': 1,  # 工作进程数
    'recycle': 500,  # 每个工作进程处理500个任务后重启
    'timeout': 60,  # 任务超时时间
    'compress': True,
    'save_limit': 250,  # 保存最多250个任务结果
    'queue_limit': 200,  # 队列最大任务数
    'cpu_affinity': 1,
    'label': 'Django Q',
    "max_attempts": 2,  # 最多尝试一次，避免无限重发
    # 使用 Django ORM 作为后端（无需 Redis）
    'orm': 'default',
}


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


from .config.config_loader import load_config

env_config = load_config()

ALLOWED_HOSTS = env_config.get("ALLOWED_HOSTS", [])

DATABASES = {
    'default': {
        'ENGINE': env_config["DATABASE"]["ENGINE"],
        'NAME': env_config["DATABASE"]["NAME"],
        'USER': env_config["DATABASE"]["USER"],
        'PASSWORD': env_config["DATABASE"]["PASSWORD"],
        'HOST': env_config["DATABASE"]["HOST"],
        'PORT': env_config["DATABASE"]["PORT"],

        # 关键：保持连接 60 秒，自动重连
        'CONN_MAX_AGE': 0,
    }
}

# 如果是 MySQL，追加 OPTIONS
if env_config["DATABASE"]["ENGINE"] == 'django.db.backends.mysql':
    DATABASES['default']['OPTIONS'] = {
        'charset': 'utf8mb4',
        'use_unicode': True,
        'autocommit': True,  # 关键：避免 InterfaceError (0, '')
        'init_command': (
            "SET character_set_connection=utf8mb4, "
            "collation_connection=utf8mb4_unicode_ci"
        ),
    }


STORAGE_MODE = env_config["STORAGE_MODE"]
DEFAULT_FILE_STORAGE = "bot_core.storage_backends.get_default_storage"

if STORAGE_MODE == "cos":
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
    AWS_ACCESS_KEY_ID = env_config["COS"]["SECRET_ID"]
    AWS_SECRET_ACCESS_KEY = env_config["COS"]["SECRET_KEY"]
    AWS_STORAGE_BUCKET_NAME = env_config["COS"]["BUCKET"]
    AWS_S3_ENDPOINT_URL = env_config["COS"]["ENDPOINT"]

elif STORAGE_MODE == "s3":
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
    AWS_ACCESS_KEY_ID = env_config["AWS"]["ACCESS_KEY_ID"]
    AWS_SECRET_ACCESS_KEY = env_config["AWS"]["SECRET_ACCESS_KEY"]
    AWS_STORAGE_BUCKET_NAME = env_config["AWS"]["BUCKET"]
    AWS_S3_REGION_NAME = env_config["AWS"]["REGION"]

TELEGRAM_BOT_TOKEN = env_config["TELEGRAM_BOT_TOKEN"]

REPORT_DEFAULT_USER_ID = env_config.get("REPORT_DEFAULT_USER_ID", 1)