# Generated by Django 4.2.26 on 2025-11-24 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelethonAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(verbose_name='API ID')),
                ('api_hash', models.CharField(max_length=64, verbose_name='API Hash')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Phone Number')),
                ('session_string', models.TextField(blank=True, help_text='Telethon 会话的字符串表示，用于免密码登录。', verbose_name='Session String')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('logging_in', 'Logging in'), ('authorized', 'Authorized'), ('banned', 'Banned'), ('limited', 'Limited'), ('error', 'Error')], default='idle', max_length=20, verbose_name='Status')),
                ('limited_until', models.DateTimeField(blank=True, help_text='账号被限制操作的时间，在此之前不会被选为执行任务的账号。', null=True, verbose_name='Limited Until')),
                ('error_message', models.TextField(blank=True, verbose_name='Last Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_telethon_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Telethon Account',
                'verbose_name_plural': 'Telethon Accounts',
                'ordering': ['-updated_at'],
            },
        ),
    ]
