# Generated by Django 4.2.26 on 2025-11-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telethon_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telethonaccount',
            name='session_string',
            field=models.TextField(blank=True, help_text='Telethon 会话的字符串表示，用于免密码登录。', null=True, verbose_name='Session String'),
        ),
    ]
