# Generated by Django 4.2.26 on 2025-11-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telethon_account', '0002_alter_telethonaccount_session_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='telethonaccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
    ]
