# Generated by Django 4.2.26 on 2025-11-24 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('telethon_account', '0003_telethonaccount_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='telethonaccount',
            name='last_used',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
    ]
