# Generated by Django 4.2.26 on 2025-11-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telethon_account', '0004_telethonaccount_last_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='telethonaccount',
            name='request_count',
            field=models.IntegerField(default=0, verbose_name='Request Count'),
        ),
    ]
