# Generated by Django 4.2 on 2025-12-25 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tgusers', '0001_initial'),
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='悬赏标题')),
                ('description', models.TextField(blank=True, verbose_name='悬赏描述')),
                ('reward_coins', models.PositiveIntegerField(default=0, verbose_name='奖励金币')),
                ('max_submissions', models.PositiveIntegerField(blank=True, null=True, verbose_name='最大提交数')),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='places.place')),
            ],
            options={
                'verbose_name': '悬赏活动',
                'verbose_name_plural': '悬赏活动',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=200, verbose_name='候选人姓名')),
                ('note', models.TextField(blank=True, verbose_name='补充信息')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '通过'), ('rejected', '不通过')], default='pending', max_length=10, verbose_name='审核状态')),
                ('review_note', models.TextField(blank=True, verbose_name='审核备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='collect.campaign')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tgusers.telegramuser')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tgusers.telegramuser')),
            ],
            options={
                'verbose_name': '悬赏提交',
                'verbose_name_plural': '悬赏提交',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(verbose_name='消耗积分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='兑换时间')),
                ('status', models.CharField(choices=[('completed', '已完成'), ('refunded', '已退回'), ('appealed', '申诉中')], default='completed', max_length=20, verbose_name='状态')),
                ('appeal_reason', models.TextField(blank=True, verbose_name='申诉理由')),
                ('appeal_at', models.DateTimeField(blank=True, null=True, verbose_name='申诉时间')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='退回时间')),
                ('marketing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.marketing')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.place')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tgusers.telegramuser')),
            ],
            options={
                'verbose_name': '兑换记录',
                'verbose_name_plural': '兑换记录',
            },
        ),
        migrations.CreateModel(
            name='CampaignNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mygroup_id', models.IntegerField(blank=True, null=True, verbose_name='MyGroup ID')),
                ('notify_channel_id', models.BigIntegerField(verbose_name='通知频道 chat_id')),
                ('message_id', models.BigIntegerField(verbose_name='通知消息 message_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='collect.campaign')),
            ],
            options={
                'verbose_name': '悬赏通知记录',
                'verbose_name_plural': '悬赏通知记录',
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['campaign', 'status'], name='collect_sub_campaig_4c2695_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignnotification',
            index=models.Index(fields=['notify_channel_id', 'message_id'], name='collect_cam_notify__e78751_idx'),
        ),
    ]
