# Generated by Django 4.2 on 2025-12-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='note',
            new_name='extra_info',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='candidate_name',
        ),
        migrations.AddField(
            model_name='submission',
            name='attractiveness',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='颜值评价'),
        ),
        migrations.AddField(
            model_name='submission',
            name='birth_year',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='出生年份'),
        ),
        migrations.AddField(
            model_name='submission',
            name='bust_info',
            field=models.CharField(blank=True, max_length=240, verbose_name='胸围信息'),
        ),
        migrations.AddField(
            model_name='submission',
            name='bust_size',
            field=models.CharField(blank=True, max_length=50, verbose_name='胸围大小'),
        ),
        migrations.AddField(
            model_name='submission',
            name='nickname',
            field=models.CharField(default='', max_length=200, verbose_name='技师号码'),
            preserve_default=False,
        ),
    ]
