# Generated by Django 4.2 on 2025-12-26 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_staff_attractiveness_remove_staff_birth_year_and_more'),
        ('collect', '0002_rename_note_submission_extra_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='collect_sub_campaig_4c2695_idx',
        ),
        migrations.AddField(
            model_name='submission',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
        migrations.AddField(
            model_name='submission',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='places.staff'),
        ),
    ]
