# Generated by Django 4.2 on 2025-12-26 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_alter_submission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collect.campaign'),
        ),
    ]
