# Generated by Django 4.2 on 2025-12-30 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0004_alter_submission_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='submission_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '通过'), ('rejected', '不通过')], default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='collect.submission')),
            ],
        ),
    ]
