# Generated by Django 4.2 on 2026-04-08 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_place_first_letter_placeformername'),
        ('collect', '0005_submissionphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='place_name',
            field=models.CharField(blank=True, help_text='用户提交的场所名，无需提前存在', max_length=200, null=True, verbose_name='提交的场所名称'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='places.place', verbose_name='指定场所（不选则为全平台悬赏）'),
        ),
    ]
