# Generated by Django 4.2 on 2026-04-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0006_submission_place_name_alter_campaign_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignnotification',
            name='discuss_message_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='讨论组对应消息ID'),
        ),
    ]
