# Generated by Django 4.2 on 2025-12-25 04:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tgusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='报告内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='report_images/', verbose_name='报告图片')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='报告状态')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_note', models.TextField(blank=True, null=True, verbose_name='审核备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('point', models.IntegerField(default=0, verbose_name='报告积分')),
                ('reporter', models.ForeignKey(db_column='reporter_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to='tgusers.telegramuser', to_field='user_id', verbose_name='报告提交者')),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='reviewed_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to='tgusers.telegramuser', to_field='user_id', verbose_name='审核人')),
            ],
            options={
                'verbose_name': '用户报告',
                'verbose_name_plural': '用户报告',
                'ordering': ['-created_at'],
            },
        ),
    ]
