# Generated by Django 4.2 on 2025-12-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='place_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='场所名'),
        ),
    ]
