# Generated by Django 4.2 on 2026-01-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_place_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布日期'),
        ),
    ]
