# Generated by Django 4.2 on 2025-11-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='按鈕文字')),
                ('type', models.CharField(choices=[('url', 'URL 按鈕'), ('callback', '回調按鈕')], default='url', max_length=20, verbose_name='類型')),
                ('url', models.URLField(blank=True, null=True, verbose_name='按鈕連結')),
                ('callback_data', models.CharField(blank=True, max_length=100, null=True, verbose_name='回調數據')),
            ],
        ),
        migrations.CreateModel(
            name='CarouselConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='輪播名稱')),
                ('chat_id', models.BigIntegerField(verbose_name='群聊/頻道 ID')),
                ('message_text', models.TextField(blank=True, default='', verbose_name='輪播文字')),
                ('interval', models.IntegerField(default=30, verbose_name='輪播間隔（分鐘）')),
                ('page_size', models.IntegerField(default=5, verbose_name='每頁數量')),
                ('delete_previous', models.BooleanField(default=False, verbose_name='刪除上一條')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='是否置頂')),
                ('last_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='上一條消息 ID')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='上次發送時間')),
                ('total_sent_count', models.IntegerField(default=0, verbose_name='總發送次數')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('function_name', models.CharField(max_length=50, unique=True, verbose_name='函數標識')),
                ('data_fetcher', models.CharField(help_text="函數路徑，如 'myapp.tasks.fetch_articles'", max_length=200, verbose_name='數據獲取函數')),
                ('buttons', models.ManyToManyField(blank=True, to='tgfunc_carousel.carouselbutton', verbose_name='文字按鈕')),
            ],
            options={
                'verbose_name': '輪播配置',
                'verbose_name_plural': '輪播配置',
            },
        ),
    ]
