# --- 状态定义 ---
REPORT_WAITING_FOR_MERCHANT_USERNAME = 501
REPORT_WAITING_FOR_IMAGE = 502
REPORT_WAITING_FOR_CONTENT = 503
REPORT_WAITING_FOR_CONFIRMATION = 504

(REVIEWING_REPORT, INPUT_REPORT_POINTS, INPUT_REPORT_REASON ,
 CONFIRM_APPROVAL, CONFIRM_REJECTION)= range(505,510)

INPUT_REPORT_PLACE = 520
