# Generated by Django 4.2 on 2025-12-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_chat_id', models.BigIntegerField(db_index=True, help_text='群组 chat_id', unique=True)),
                ('group_username', models.CharField(blank=True, help_text='群组 @username', max_length=255, null=True)),
                ('main_channel_id', models.BigIntegerField(blank=True, help_text='主频道 chat_id', null=True)),
                ('report_channel_id', models.BigIntegerField(blank=True, help_text='报告频道 chat_id', null=True)),
                ('notify_channel_id', models.BigIntegerField(blank=True, help_text='通知频道 chat_id', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
