# Generated by Django 4.2 on 2025-12-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygroups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygroup',
            name='group_name',
            field=models.CharField(blank=True, help_text='群组名称', max_length=255, null=True),
        ),
    ]
