# Generated by Django 4.2 on 2026-01-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygroups', '0002_mygroup_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygroup',
            name='main_channel_username',
            field=models.CharField(blank=True, help_text='主频道 @username', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mygroup',
            name='notify_channel_username',
            field=models.CharField(blank=True, help_text='通知频道 @username', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mygroup',
            name='report_channel_username',
            field=models.CharField(blank=True, help_text='报告频道 @username', max_length=255, null=True),
        ),
    ]
