# Generated by Django 4.2 on 2026-04-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygroups', '0003_mygroup_main_channel_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygroup',
            name='notify_discuss_group_id',
            field=models.BigIntegerField(blank=True, help_text='频道的讨论组', null=True),
        ),
    ]
