# Generated by Django 4.2 on 2025-12-28 13:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tgusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='抽奖标题')),
                ('description', models.TextField(verbose_name='兑奖说明')),
                ('required_points', models.IntegerField(verbose_name='参与所需积分')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='活动开始时间')),
                ('end_time', models.DateTimeField(verbose_name='开奖时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否正在进行')),
                ('is_drawn', models.BooleanField(default=False, verbose_name='是否已开奖')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('result_message', models.TextField(blank=True, null=True, verbose_name='开奖结果消息')),
                ('group_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='群消息ID')),
                ('group_id', models.BigIntegerField(blank=True, null=True, verbose_name='发布的群ID')),
            ],
            options={
                'verbose_name': '抽奖活动',
                'verbose_name_plural': '抽奖活动',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='奖品名称')),
                ('quantity', models.IntegerField(verbose_name='奖品数量')),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='lottery.lottery', verbose_name='所属抽奖')),
            ],
            options={
                'verbose_name': '奖品',
                'verbose_name_plural': '奖品',
            },
        ),
        migrations.CreateModel(
            name='LotteryWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='中奖时间')),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='lottery.lottery', verbose_name='所属抽奖')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.prize', verbose_name='获得奖项')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lottery_wins', to='tgusers.telegramuser', verbose_name='中奖用户')),
            ],
            options={
                'verbose_name': '中奖记录',
                'verbose_name_plural': '中奖记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LotteryParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participated_at', models.DateTimeField(auto_now_add=True, verbose_name='参与时间')),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='lottery.lottery', verbose_name='所属抽奖')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lottery_participations', to='tgusers.telegramuser', verbose_name='参与用户')),
            ],
            options={
                'verbose_name': '抽奖参与记录',
                'verbose_name_plural': '抽奖参与记录',
            },
        ),
    ]
